# Generated by Django 4.2.10 on 2024-07-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('grad_year', models.IntegerField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='alumni_images/')),
            ],
        ),
    ]
